### ISSUE TITLE
Unable to edit input when prefix is added

### ISSUE THREAD

**Issue by KuzinVadym** [jsillitoe/react-currency-input#11]
when you specify prefix for example "$", CurrencyInput not working and onChange action give you always last 1 character and  if you didn't use prefix field at all, CurrencyInput working normal
I use react and react-dom  "^15.4.2",

**Comment by jsillitoe** [comment]
The last release I published a couple days ago introduced a pretty serious bug that basically broke everything.  My apologies!  I've published a new release v1.2.3 that should fix it.  As always, included in the release is a number of new unit tests.  Thank you submitting this issue!
