### ISSUE TITLE
Function custom props don't get applied to input

### ISSUE THREAD

**Issue by tegon** [jsillitoe/react-currency-input#12]
I use this component with an `onKeyUp` event to trigger an API request. This used to work, but it stopped after this commit: https://github.com/jsillitoe/react-currency-input/commit/94e30dd49d8fa3ec8ceb07014d70bb9b2c45f93f.
This happens because `JSON.stringify` cannot serialize functions.
I understand this was a patch to support older environments, but is also broken for other keyboard events.
I see that in one of the last versions you had added the `Object.assign` polyfill. In my opinion, this is a better solution to the problem.
You could also have used the spread operator.
```js
let customProps = {...props};
```
It is also an ES6 feature, but I supposed it is ok to use it here since it is already being used in [master](https://github.com/jsillitoe/react-currency-input/blob/master/src/index.js#L176).
Anyway, I've downgraded to a previous version to fix my website for now, but I'll be happy to help if you wanna discuss a solution.

Thanks

**Comment by jsillitoe** [comment]
I have to admit, I was not exactly thrilled with using the `JSON.stringify` function, but it didn't occur to me that other devs were attaching functions.  I had to include the stage-3 presets from babel but I've gone ahead and switched to the spread operator.  Behind the scenes it uses Object.assign and includes a polyfill.  Sorry for breaking the component for you, but version 1.2.4 should now restore it for you as well as keep support for the other environments.

**Comment by tegon** [comment]
No problem, thank you for the quick fix! 
Here is my website: https://www.neocambio.com.br/dolar/sp/sao-paulo?deadline=1
You can type the amount of dollars in the input, and when you're done - onKeyUp - an API request is sent to update the prices.

**Comment by jsillitoe** [comment]
That's awesome!  Thank you for sharing.
