### ISSUE TITLE
Return negative number as raw value when numberIsNegative

### ISSUE THREAD

**Issue by tiago-pereira** [jsillitoe/react-currency-input#14]
The raw value passed to `onChange(masked, raw, event)` ignores negative values.

```
onChange={(masked, raw) => {
    console.log('allowNegative: ', allowNegative);
    console.log('masked: ', masked);
    console.log('raw: ', raw);
}}
```

![image](https://cloud.githubusercontent.com/assets/13859128/23519663/803aadea-ff56-11e6-9026-e1eff8f3ee71.png)

Shouldn't we return the negative raw value instead?

**Comment by jsillitoe** [comment]
Yes it should.  Thank you for the pull request!

**Comment by jsillitoe** [comment]
I applied and published your patch.  It is release in version 1.2.5
