### ISSUE TITLE
don't pass value directly to onChange (to be on par with React's default input handling)

### ISSUE THREAD

**Issue by florianbepunkt** [jsillitoe/react-currency-input#18]
By default React passes an event to onChange function – so you can access the value via event.target.value. Would be nice if this component would follow the same pattern. When you have larger forms it helps to keep code nice and clean if you don't need seperate handlers for every component.

**Comment by florianbepunkt** [comment]
#19 PR

**Comment by jsillitoe** [comment]
I agree with you however, this would break existing implementations.  When we are ready to do another major release i'll include this.  Thank you for the report and the patch!

**Comment by indapublic** [comment]
+1, Need this for using in redux form

**Comment by josefheld** [comment]
+1

**Comment by jsillitoe** [comment]
New with version 1.3.0,  instead of using the onChange callback, use onChangeEvent.  The signature for the new function looks like onChangeEvent(event, maskedvalue, floatvalue).  Hopefully this works for your use case.
