### ISSUE TITLE
Trouble with Synthetic Events

### ISSUE THREAD

**Issue by igorsantos07** [jsillitoe/react-currency-input#23]
For no apparent (?) reason I started seeing warnings/errors in my console referring to this doc page: [Event Pooling](https://facebook.github.io/react/docs/events.html#event-pooling). That happened because I was using `e.target.name` to define which property of my object I should update, but it started to fail. I work-arounded that using a function that returns a function, scoping the field name instead of relying in the target `name` (like `onChange: name => (masked, value, e) => [...]`)

It seems that the inner implementation should call `event.persist()` somewhere, before passing it down to the handler we specify :)

**Comment by jsillitoe** [comment]
Added.  Thanks!
