### ISSUE TITLE
React.createClass becoming deprecated

### ISSUE THREAD

**Issue by dubielzyk** [jsillitoe/react-currency-input#26]
`CurrencyInput: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

I also get this (though I'm not sure if that's the same):
`Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by bad6e** [comment]
They are both related. 

`import PropTypes from 'prop-types'`
and then drop the `React` in front of the `propTypes`

```json
"react": "^15.5.0",
"prop-types": "^15.5.0",
```

**Comment by dubielzyk** [comment]
As it's being deprecated, is there any plans to support this without the prop-types package?

**Comment by jsillitoe** [comment]
I've added in the updates for react v15.  Thanks zhuangya!
