### ISSUE TITLE
input component on IE10 fails with parseFloat function

### ISSUE THREAD

**Issue by wxqp** [jsillitoe/react-currency-input#27]
in code line 89, file src/index.js

`initialValue = Number.parseFloat(initialValue);`

running on IE10, throw next error

![react](https://cloud.githubusercontent.com/assets/5313634/25687022/1cfb5b5c-3030-11e7-86f6-70288c9c0f59.PNG)
![react2](https://cloud.githubusercontent.com/assets/5313634/25687023/1cfd9d22-3030-11e7-97ee-d636c7383f55.PNG)

this, doesn't happen on chrome, firefox, edge.

this was solved, change this line to

> `initialValue = initialValue * 1;`

**Comment by zhuangya** [comment]
IE* does not support parseFloat: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseFloat

i think i can send a PR to add polyfill for this
