### ISSUE TITLE
A way to add dollar sign as prefix?

### ISSUE THREAD

**Issue by jsantana90** [jsillitoe/react-currency-input#3]
Hello, thanks for this component!

I was wondering if there's a way to add a $ symbol as prefix using this component?

**Comment by jsillitoe** [comment]
That is not currently supported in this component, but i like the feature and it will be simple enough to implement.  I'll take a crack at it.

**Comment by jsillitoe** [comment]
Just added support, you can set the $ prefix like this:
``
<CurrencyInput prefix="$" />
``

**Comment by jsantana90** [comment]
oh wow thanks!

btw, I get an error when I start typing

`Unknown prop `suffix` on <input> tag. Remove this prop from the element`

the component looks like this:
```jsx
<CurrencyInput
  className={`form-control text-xs-right ${styles.fontSize} ${styles.directionRight}`}
  inputType="text"
  placeholder="123456"
  prefix="$"
  readOnly="readOnly"
  style={{ borderColor: style.borderColor }}
  value={numbersInInput}
/>
```

**Comment by jsillitoe** [comment]
Thanks for the heads up.  Just released the fix for that error.  use version 1.0.9
