### ISSUE TITLE
providing initial value as the integer 0, doesn't show any mask

### ISSUE THREAD

**Issue by viniciusdacal** [jsillitoe/react-currency-input#33]
If you provide the initial value as the integer 0, it should show the expected mask
0 => "$0.00".

I noticed we have tests covering the case for the string "0" but not for the integer.
I can open a pull request fixing that.

**Comment by jsillitoe** [comment]
Good catch,  Just added the fix and will include in the next release.

**Comment by viniciusdacal** [comment]
@jsillitoe would be great to have an option for that as well. I mean, in some cases people rely on that behaviour.

I had a case recently, the initial values were 0, but the input should show the placeholder with the text `minValue is ...` instead of the mask. Weird situations, but worth having an option like `displayZero: bool` or any better name.

**Comment by jsillitoe** [comment]
Sounds like it is worth a look, please open a new issue and I'll see what that would take.
