### ISSUE TITLE
raw value

### ISSUE THREAD

**Issue by viniciusdacal** [jsillitoe/react-currency-input#4]
First of all, thank you for this component.
I would like to know if there is a way to get the raw value, as a float number, as in the example:
"$ 1.30" => 1.30 

Maybe we could receive this value as the second parameter in the onChange callback function.

**Comment by jsillitoe** [comment]
The underlying raw value is really just a string of digits,  so I think it is probably out of scope for this component to try and convert that to a float.  I recommend just using the [Number.parseFloat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseFloat) function on the masked value (you may need to trim off the prefix and extra spaces if any).

**Comment by viniciusdacal** [comment]
I see that point, It would be simple to convert american masked values with parseFloat, but we would get a different value for non american formats, such as `R$ 1.000,00`.

Mask is mainly useful as a visual thing, I think it would be useful receiving a raw value inside the callback

There is already a logic to get the raw value, inside the function `mask`. My ideia is to reuse this logic. 
I will try to open a pull request, if it makes sense we could merge, what do you think?

**Comment by jsillitoe** [comment]
Sounds good to me, Thank you!
