### ISSUE TITLE
bump version and republish package

### ISSUE THREAD

**Issue by malbernaz** [jsillitoe/react-currency-input#64]
this package wasn't republished since the last changes.

**Comment by dankirlin** [comment]
Are there any plans to republish this in the immediate future? It seems this comment was from over a month ago and this package hasn't been published in 5 months.

**Comment by selected-pixel-jameson** [comment]
+1

**Comment by dankirlin** [comment]
Is there any update on this?

**Comment by jsillitoe** [comment]
Sorry everyone.  Been distracted with other things.  I just published and update.  now version 1.3.5
