### ISSUE TITLE
onChange event does not work.

### ISSUE THREAD

**Issue by wellmonge** [jsillitoe/react-currency-input#65]
Anyone face this problem, with simple  code as present at Readme onChangeEvent does not trigger
onChange event?

` 
handleChange` = (event, value, maskedValue) => {
    this.setState({ amount: value })
  }

  render() {
    const { amount } = this.state

    return (
      <CurrencyInput value={amount} onChange={this.handleChange} />
    )
  }
`

**Comment by nkohirkar** [comment]
I am seeing the same issue. Can someone please take a look at this?

**Comment by acomito** [comment]
onChangeEvent is the new event to use. But that's in the latest version, which doesn't work in safari. So if you downgrade to 1.2.6, you can get this working in safari-- but then you need to use onChange.
