### ISSUE TITLE
inputType=number is troublesome with any mask

### ISSUE THREAD

**Issue by igorsantos07** [jsillitoe/react-currency-input#7]
If the developer enables any mask-related feature - such as prefix, suffix or separators - an input `type=number` or `tel` would trigger errors, because most of those characters would be invalid in such input types.

If that option is really to be used, at least disclose in the documentation/README that it should not be used together with mask-related attributes.

![screenshot_010](https://cloud.githubusercontent.com/assets/532299/21835538/e5595b4c-d7a4-11e6-9161-187f70995634.png)

**Comment by jsillitoe** [comment]
Agreed.  I'll add a note to the README

**Comment by igorsantos07** [comment]
Done already :)
