### ISSUE TITLE
PropTypes Peer Dependency

### ISSUE THREAD

**Issue by dinkzilla** [jsillitoe/react-currency-input#72]
In the package file you list a peer dependency of:

`"prop-types": "^16.0.0",`

But the current highest version of [prop-types is 15.6.1](https://www.npmjs.com/package/prop-types).

Npm throws errors as a result when adding your package.

**Comment by agusgar** [comment]
Have this same issue. Are you planning to fix this?

**Comment by jsharpe** [comment]
My PR #80 resolves this issue.
