### ISSUE TITLE
Focus in Safari

### ISSUE THREAD

**Issue by menezee** [jsillitoe/react-currency-input#74]
Using version 1.3.6 with React 16.3.2 in Safari, the field starts autofocused. I need it to follow the tabIndex as well, but everytime I type it tries to focus back in the CurrencyInput component.

Any thoughts?

**Comment by dturakhia** [comment]
+1 Facing similar issues on Safari

**Comment by ybreezy** [comment]
Did anyone figure this out? It's driving me insane
