### ISSUE TITLE
Test framework shouldn't be included as dev dependency

### ISSUE THREAD

**Issue by havivian** [jsillitoe/react-currency-input#76]
The `package.json` currently lists `sinon` as a dev dependency, requiring the entire framework to be installed as a part of installing `react-currency-input`

**Comment by ericblade** [comment]
... i think that's the purpose of dev dependencies.  From npm docs: With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies.

At least, I've never heard of not putting the requirements to test inside the dev dependencies.  Is that the norm somewhere? I'd like to hear about that.

**Comment by jsharpe** [comment]
I think what was meant was dependency rather than dev dependency. PR #80 corrects this.
